// Mocks generated by Mockito 5.0.8 from annotations
// in ditonton/test/presentation/pages/top_rated_tv_series_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:ditonton/common/state_enum.dart' as _i3;
import 'package:ditonton/domain/entities/tv_series.dart' as _i4;
import 'package:ditonton/presentation/provider/top_rated_tv_series_notifier.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TopRatedTVSeriesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTVSeriesNotifier extends _i1.Mock
    implements _i2.TopRatedTVSeriesNotifier {
  MockTopRatedTVSeriesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i3.RequestState.Empty) as _i3.RequestState);
  @override
  List<_i4.TVSeries> get tvSeries =>
      (super.noSuchMethod(Invocation.getter(#tvSeries),
          returnValue: <_i4.TVSeries>[]) as List<_i4.TVSeries>);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i5.Future<void> fetchTopRated() =>
      (super.noSuchMethod(Invocation.method(#fetchTopRated, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  void addListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
